---

project_name: windsor

version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: windows
    env:
      - CGO_ENABLED=0
    main: ./cmd/windsor
    goos:
      - windows
    goarch:
      - amd64
    binary: windsor.exe
    ldflags:
      - "-X 'github.com/{{ .Env.GITHUB_REPOSITORY }}/cmd.version={{ .Version }}'"
      - "-X 'github.com/{{ .Env.GITHUB_REPOSITORY }}/pkg/secrets.version={{ .Version }}'"
      - "-X 'github.com/{{ .Env.GITHUB_REPOSITORY }}/cmd.commitSHA={{ .Env.GITHUB_SHA }}'"

#  - id: unix
#    env:
#      - CGO_ENABLED=0
#    main: ./cmd/windsor
#    goos:
#      - darwin
#      - linux
#    goarch:
#      - amd64
#      - arm64
#    binary: windsor
#    ldflags:
#      - "-X 'github.com/{{ .Env.GITHUB_REPOSITORY }}/cmd.version={{ .Version }}'"
#      - "-X 'github.com/{{ .Env.GITHUB_REPOSITORY }}/pkg/secrets.version={{ .Version }}'"
#      - "-X 'github.com/{{ .Env.GITHUB_REPOSITORY }}/cmd.commitSHA={{ .Env.GITHUB_SHA }}'"

# Archive configuration
archives:
  - id: windsor
    formats: ["tar.gz"]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

# Release configuration
release:
  github:
    owner: windsorcli
    name: cli
  draft: false
  prerelease: auto

binary_signs:
  - cmd: gpg
    args: 
      - --output
      - "${signature}"
      - --detach-sign
      - "${artifact}"
    signature: ${artifact}_{{ .Os }}_{{ .Arch }}.sig
    artifacts: binary

signs:
  - artifacts: checksum

# brews:
#   - name: windsor
#     directory: Formula
#     repository:
#       owner: windsorcli
#       name: homebrew-cli
#       branch: main
#       token: "{{ .Env.HOMEBREW_CLI_WRITE_PAT }}"
#     homepage: "https://windsorcli.github.io"      
#     description: "The Windsor Command Line Interface"
#     ids:
#       - windsor

chocolateys:
  - name: windsor
    ids:
      - windows
    package_source_url: https://github.com/windsorcli/cli
    owners: Windsor CLI
    title: Windsor CLI
    authors: Windsor CLI Team
    project_url: https://windsorcli.github.io
    icon_url: https://windsorcli.github.io/icon.png
    copyright: "2025 Windsor CLI Team"
    license_url: https://github.com/windsorcli/cli/blob/main/LICENSE
    require_license_acceptance: false
    project_source_url: https://github.com/windsorcli/cli
    docs_url: https://windsorcli.github.io
    bug_tracker_url: https://github.com/windsorcli/cli/issues
    tags: "cli windows command-line"
    summary: "The Windsor Command Line Interface"
    description: |
      The Windsor CLI assists your cloud native development workflow.
      This package provides the Windows installer for Windsor CLI.
      
      After installation, add the following line to your PowerShell profile to enable shell integration:
      ```powershell
      Invoke-Expression (& windsor hook powershell)
      ```
      
      Your PowerShell profile is located at: $PROFILE
    release_notes: "https://github.com/windsorcli/cli/releases/tag/v{{ .Version }}"
    skip_publish: false
    api_key: "{{ .Env.CHOCOLATEY_API_KEY }}"
    source_repo: "https://push.chocolatey.org/"
