---

project_name: windsor

version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: windsor
    env:
      - CGO_ENABLED=0
    main: ./cmd/windsor
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - arm64
      - amd64
    ldflags:
      - "-X 'github.com/{{ .Env.GITHUB_REPOSITORY }}/cmd.version={{ .Version }}'"
      - "-X 'github.com/{{ .Env.GITHUB_REPOSITORY }}/pkg/secrets.version={{ .Version }}'"
      - "-X 'github.com/{{ .Env.GITHUB_REPOSITORY }}/cmd.commitSHA={{ .Env.GITHUB_SHA }}'"

# Archive configuration
archives:
  - id: windsor
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

# Release configuration
release:
  github:
    owner: windsorcli
    name: cli
  draft: false
  prerelease: auto

binary_signs:
  - cmd: gpg
    args: 
      - --output
      - "${signature}"
      - --detach-sign
      - "${artifact}"
    signature: ${artifact}_{{ .Os }}_{{ .Arch }}.sig
    artifacts: binary

signs:
  - artifacts: checksum

brews:
  - name: windsor
    ids:
      - windsor
    directory: Formula
    skip_upload: auto
    repository:
      owner: windsorcli
      name: homebrew-cli
      branch: main
      token: "{{ .Env.HOMEBREW_CLI_WRITE_PAT }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    homepage: "https://windsorcli.github.io"
    description: "The Windsor Command Line Interface"
    license: "MPL-2.0"
