---

project_name: windsor

version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  # - id: linux_amd64
  #   env:
  #     - CGO_ENABLED=0
  #   main: ./cmd/windsor
  #   goos:
  #     - linux
  #   goarch:
  #     - amd64
  #   ldflags:
  #     - "-X 'github.com/{{ .Env.GITHUB_REPOSITORY }}/cmd.version={{ .Version }}'"
  #     - "-X 'github.com/{{ .Env.GITHUB_REPOSITORY }}/cmd.commitSHA={{ .Env.GITHUB_SHA }}'"

  # - id: linux_arm64
  #   env:
  #     - CGO_ENABLED=0
  #   main: ./cmd/windsor
  #   goos:
  #     - linux
  #   goarch:
  #     - arm64
  #   ldflags:
  #     - "-X 'github.com/{{ .Env.GITHUB_REPOSITORY }}/cmd.version={{ .Version }}'"
  #     - "-X 'github.com/{{ .Env.GITHUB_REPOSITORY }}/cmd.commitSHA={{ .Env.GITHUB_SHA }}'"

  # - id: windows_amd64
  #   env:
  #     - CGO_ENABLED=0
  #   main: ./cmd/windsor
  #   goos:
  #     - windows
  #   goarch:
  #     - amd64
  #   ldflags:
  #     - "-X 'github.com/{{ .Env.GITHUB_REPOSITORY }}/cmd.version={{ .Version }}'"
  #     - "-X 'github.com/{{ .Env.GITHUB_REPOSITORY }}/cmd.commitSHA={{ .Env.GITHUB_SHA }}'"

  - id: darwin_amd64
    env:
      - CGO_ENABLED=0
    main: ./cmd/windsor
    goos:
      - darwin
    goarch:
      - amd64
    ldflags:
      - "-X 'github.com/{{ .Env.GITHUB_REPOSITORY }}/cmd.version={{ .Version }}'"
      - "-X 'github.com/{{ .Env.GITHUB_REPOSITORY }}/cmd.commitSHA={{ .Env.GITHUB_SHA }}'"

  - id: darwin_arm64
    env:
      - CGO_ENABLED=0
    main: ./cmd/windsor
    goos:
      - darwin
    goarch:
      - arm64
    ldflags:
      - "-X 'github.com/{{ .Env.GITHUB_REPOSITORY }}/cmd.version={{ .Version }}'"
      - "-X 'github.com/{{ .Env.GITHUB_REPOSITORY }}/cmd.commitSHA={{ .Env.GITHUB_SHA }}'"

# Archive configuration
archives:
  # - id: linux_arm64
  #   format: ["zip", "tar.gz"]
  # - id: windows_amd64
  #   format: ["zip", "tar.gz"]
  - id: darwin_amd64
    format: ["zip", "tar.gz"]
  - id: darwin_arm64
    format: ["zip", "tar.gz"]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

# Release configuration
release:
  github:
    owner: windsorcli
    name: cli
  draft: false
  prerelease: false

binary_signs:
  - cmd: gpg
    args: 
      - --output
      - "${signature}"
      - --detach-sign
      - "${artifact}"
    signature: ${artifact}_{{ .Os }}_{{ .Arch }}.sig
    artifacts: binary

signs:
  - artifacts: checksum

brews:
  - name: windsor
    directory: Formula
    skip_upload: false
    repository:
      owner: windsorcli
      name: homebrew-cli
      branch: main
      token: "{{ .Env.HOMEBREW_CLI_WRITE_PAT }}"
    homepage: "https://windsorcli.github.io"      
    description: "The Windsor Command Line Interface"
    ids:
      - darwin_amd64
      - darwin_arm64
