version: '3'

tasks:
  setup:
    desc: Set up the project
    cmds:
      - go mod tidy
      - go mod verify
      - go test -v ./cmd/windsor

  build:
    desc: Build the Windsor CLI for the current platform
    cmds:
      - cmd: mkdir -p dist
        platforms: [linux, darwin]
      - cmd: powershell -Command "New-Item -ItemType Directory -Force -Path dist"
        platforms: [windows]
      - cmd: GOOS=linux GOARCH=amd64 go build -o dist/windsor ./cmd/main.go
        platforms: [linux]
      - cmd: GOOS=linux GOARCH=arm64 go build -o dist/windsor ./cmd/main.go
        platforms: [linux]
      - cmd: GOOS=darwin GOARCH=amd64 go build -o dist/windsor ./cmd/main.go
        platforms: [darwin]
      - cmd: GOOS=darwin GOARCH=arm64 go build -o dist/windsor ./cmd/main.go
        platforms: [darwin]
      - cmd: GOOS=windows GOARCH=amd64 go build -o dist/windsor.exe ./cmd/main.go
        platforms: [windows]

  clean:
    desc: Clean build artifacts
    cmds:
      - cmd: rm -f dist/windsor dist/windsor-arm
        platforms: [linux, darwin]
      - cmd: powershell -Command "Remove-Item -Force dist\windsor.exe"
        platforms: [windows]

  test:
    desc: Run tests
    cmds:
      - go test ./cmd/windsor

  run:
    desc: Run the Windsor CLI
    cmds:
      - go run ./cmd/main.go {{.CLI_ARGS}}

  all:
    desc: Setup, test, and build
    cmds:
      - task: setup
      - task: test
      - task: integration-test
      - task: build

  default:
    desc: Show available tasks
    cmds:
      - task --list

  integration-test:
    desc: Run integration tests
    cmds:
      - go test ./... -tags=integration
