version: '3'

tasks:
  setup:
    desc: Set up the project
    cmds:
      - go mod tidy
      - go mod verify
      - go install github.com/spf13/cobra-cli@latest
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - go test -v ./cmd

  build:
    desc: Build the Windsor CLI for the current platform
    cmds:
      - cmd: mkdir -p dist
        platforms: [linux, darwin]
      - cmd: powershell -Command "New-Item -ItemType Directory -Force -Path dist"
        platforms: [windows]
      - cmd: GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o dist/windsor ./cmd/windsor/main.go
        platforms: [linux]
      - cmd: GOOS=linux GOARCH=arm64 go build -ldflags="-s -w" -o dist/windsor ./cmd/windsor/main.go
        platforms: [linux]
      - cmd: GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o dist/windsor ./cmd/windsor/main.go
        platforms: [darwin]
      - cmd: GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w" -o dist/windsor ./cmd/windsor/main.go
        platforms: [darwin]
      - cmd: GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o dist/windsor.exe ./cmd/windsor/main.go
        platforms: [windows]

  clean:
    desc: Clean build artifacts
    cmds:
      - cmd: rm -f dist/windsor dist/windsor-arm
        platforms: [linux, darwin]
      - cmd: powershell -Command "Remove-Item -Force dist\windsor.exe"
        platforms: [windows]

  test:
    desc: Run unit tests with coverage (excludes integration-tagged tests)
    env:
      CI: true
    cmds:
      - cmd: |
          if [ -n "{{.CLI_ARGS}}" ]; then
            go test -covermode=atomic -coverprofile=coverage.out -run {{.CLI_ARGS}} ./api/... ./pkg/... ./cmd
          else
            go test -covermode=atomic -coverprofile=coverage.out ./api/... ./pkg/... ./cmd
          fi
        platforms: [linux, darwin]
      - cmd: powershell -NoProfile -Command "if ('{{.CLI_ARGS}}') { go test -covermode=atomic -coverprofile='coverage.out' -run '{{.CLI_ARGS}}' ./api/... ./pkg/... ./cmd } else { go test -covermode=atomic -coverprofile='coverage.out' ./api/... ./pkg/... ./cmd }"
        platforms: [windows]
      - go tool cover -html=coverage.out -o coverage.html
    silent: true

  test:integration:
    desc: Run only integration-tagged tests in cmd with coverage (-run TestIntegration by default)
    env:
      CI: true
    cmds:
      - cmd: |
          if [ -n "{{.CLI_ARGS}}" ]; then
            go test -tags=integration -v -covermode=atomic -coverprofile=coverage.out -run {{.CLI_ARGS}} ./cmd
          else
            go test -tags=integration -v -covermode=atomic -coverprofile=coverage.out -run TestIntegration ./cmd
          fi
        platforms: [linux, darwin]
      - cmd: powershell -NoProfile -Command "if ('{{.CLI_ARGS}}') { go test -tags=integration -v -covermode=atomic -coverprofile='coverage.out' -run '{{.CLI_ARGS}}' ./cmd } else { go test -tags=integration -v -covermode=atomic -coverprofile='coverage.out' -run TestIntegration ./cmd }"
        platforms: [windows]
      - cmd: |
          go tool cover -func=coverage.out | tail -1 | awk '{print "total coverage:", $NF}'
        platforms: [linux, darwin]
      - cmd: powershell -NoProfile -Command "go tool cover -func .\coverage.out 2>&1 | Select-Object -Last 1"
        platforms: [windows]

  test:all:
    desc: Run full test suite (unit + integration), write coverage.out/html and print total
    env:
      CI: true
    cmds:
      - cmd: |
          if [ -n "{{.CLI_ARGS}}" ]; then
            go test -tags=integration -covermode=atomic -coverprofile=coverage.out -run {{.CLI_ARGS}} ./api/... ./pkg/... ./cmd
          else
            go test -tags=integration -covermode=atomic -coverprofile=coverage.out ./api/... ./pkg/... ./cmd
          fi
        platforms: [linux, darwin]
      - cmd: powershell -NoProfile -Command "if ('{{.CLI_ARGS}}') { go test -tags=integration -covermode=atomic -coverprofile='coverage.out' -run '{{.CLI_ARGS}}' ./api/... ./pkg/... ./cmd } else { go test -tags=integration -covermode=atomic -coverprofile='coverage.out' ./api/... ./pkg/... ./cmd }"
        platforms: [windows]
      - cmd: go tool cover -html=coverage.out -o coverage.html
        platforms: [linux, darwin]
      - cmd: |
          go tool cover -func=coverage.out | tail -1 | awk '{print "total coverage:", $NF}'
        platforms: [linux, darwin]
      - cmd: powershell -NoProfile -Command "go tool cover -func .\coverage.out 2>&1 | Select-Object -Last 1; exit 0"
        platforms: [windows]
    silent: true

  scan:
    desc: Scan for security vulnerabilities
    cmds:
      - go install github.com/securego/gosec/v2/cmd/gosec@latest
      - gosec ./...

  run:
    desc: Run the Windsor CLI
    cmds:
      - go run ./cmd/windsor/main.go {{.CLI_ARGS}}

  all:
    desc: Setup, test, and build
    cmds:
      - task: setup
      - task: test
      - task: build

  default:
    desc: Show available tasks
    cmds:
      - task --list
