services:
  aws.test:
    environment:
      DEBUG: "0"
      ENFORCE_IAM: "1"
      IAM_SOFT_MODE: "0"
      PERSISTENCE: "1"
      SERVICES: iam,sts,kms,s3,dynamodb
    image: localstack/localstack:3.8.1
    labels:
      managed_by: windsor
      role: localstack
      wildcard: "true"
    networks:
      windsor-local:
        ipv4_address: 10.1.0.2
    restart: always
  controlplane-1.test:
    environment:
      PLATFORM: container
      TALOSSKU: 2CPU-2048RAM
    image: ghcr.io/siderolabs/talos:v1.8.1
    networks:
      windsor-local:
        ipv4_address: 10.1.0.3
    privileged: true
    read_only: true
    restart: always
    security_opt:
      - seccomp=unconfined
    tmpfs:
      - /run
      - /system
      - /tmp
    volumes:
      - type: bind
        source: /run/udev
        target: /run/udev
      - type: volume
        source: system_state
        target: /system/state
      - type: volume
        source: var
        target: /var
      - type: volume
        source: etc_cni
        target: /etc/cni
      - type: volume
        source: etc_kubernetes
        target: /etc/kubernetes
      - type: volume
        source: usr_libexec_kubernetes
        target: /usr/libexec/kubernetes
      - type: volume
        source: usr_etc_udev
        target: /usr/etc/udev
      - type: volume
        source: opt
        target: /opt
  dns.test:
    environment:
      COREDNS_CONFIG: /etc/coredns/Corefile
    image: coredns/coredns:1.11.3
    networks:
      windsor-local:
        ipv4_address: 10.1.0.4
    restart: always
    volumes:
      - type: bind
        source: ./Corefile
        target: /etc/coredns/Corefile
  gcr.test:
    environment:
      REGISTRY_PROXY_REMOTEURL: https://gcr.io
    image: registry:2.8.3
    labels:
      managed_by: windsor
      role: registry
    networks:
      windsor-local:
        ipv4_address: 10.1.0.5
    restart: always
  ghcr.test:
    environment:
      REGISTRY_PROXY_REMOTEURL: https://ghcr.io
    image: registry:2.8.3
    labels:
      managed_by: windsor
      role: registry
    networks:
      windsor-local:
        ipv4_address: 10.1.0.6
    restart: always
  git.test:
    environment:
      GIT_PASSWORD: local
      GIT_USERNAME: local
      RSYNC_EXCLUDE: .docker-cache,.terraform,data,.venv
      RSYNC_PROTECT: flux-system
      VERIFY_SSL: "false"
      WEBHOOK_URL: http://flux-webhook.private.test
    image: ghcr.io/windsor-hotel/git-livereload-server:v0.2.1
    labels:
      managed_by: windsor
      role: git-repository
    networks:
      windsor-local:
        ipv4_address: 10.1.0.7
    restart: always
    volumes:
      - type: bind
        source: ${WINDSOR_PROJECT_ROOT}
        target: /repos/mount/cli
  quay.test:
    environment:
      REGISTRY_PROXY_REMOTEURL: https://quay.io
    image: registry:2.8.3
    labels:
      managed_by: windsor
      role: registry
    networks:
      windsor-local:
        ipv4_address: 10.1.0.8
    restart: always
  registry-1.docker.test:
    environment:
      REGISTRY_PROXY_LOCALURL: https://docker.io
      REGISTRY_PROXY_REMOTEURL: https://registry-1.docker.io
    image: registry:2.8.3
    labels:
      managed_by: windsor
      role: registry
    networks:
      windsor-local:
        ipv4_address: 10.1.0.9
    restart: always
  registry.k8s.test:
    environment:
      REGISTRY_PROXY_REMOTEURL: https://registry.k8s.io
    image: registry:2.8.3
    labels:
      managed_by: windsor
      role: registry
    networks:
      windsor-local:
        ipv4_address: 10.1.0.10
    restart: always
  registry.test:
    image: registry:2.8.3
    labels:
      managed_by: windsor
      role: registry
    networks:
      windsor-local:
        ipv4_address: 10.1.0.11
    restart: always
  worker-1.test:
    environment:
      PLATFORM: container
      TALOSSKU: 4CPU-4096RAM
    image: ghcr.io/siderolabs/talos:v1.8.1
    networks:
      windsor-local:
        ipv4_address: 10.1.0.12
    privileged: true
    read_only: true
    restart: always
    security_opt:
      - seccomp=unconfined
    tmpfs:
      - /run
      - /system
      - /tmp
    volumes:
      - type: bind
        source: /run/udev
        target: /run/udev
      - type: volume
        source: system_state
        target: /system/state
      - type: volume
        source: var
        target: /var
      - type: volume
        source: etc_cni
        target: /etc/cni
      - type: volume
        source: etc_kubernetes
        target: /etc/kubernetes
      - type: volume
        source: usr_libexec_kubernetes
        target: /usr/libexec/kubernetes
      - type: volume
        source: usr_etc_udev
        target: /usr/etc/udev
      - type: volume
        source: opt
        target: /opt
      - type: bind
        source: ${WINDSOR_PROJECT_ROOT}/.volumes
        target: /var/local
networks:
  windsor-local:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/16
volumes:
  coredns_config: {}
  etc_cni: {}
  etc_kubernetes: {}
  opt: {}
  system_state: {}
  usr_etc_udev: {}
  usr_libexec_kubernetes: {}
  var: {}
