package helpers

import (
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"

	"github.com/goccy/go-yaml"
	"github.com/windsor-hotel/cli/internal/config"
	"github.com/windsor-hotel/cli/internal/context"
	"github.com/windsor-hotel/cli/internal/shell"
)

// DockerHelper is a helper struct that provides Docker-specific utility functions
type DockerHelper struct {
	ConfigHandler config.ConfigHandler
	Shell         shell.Shell
	Context       context.ContextInterface
}

// NewDockerHelper is a constructor for DockerHelper
func NewDockerHelper(configHandler config.ConfigHandler, shell shell.Shell, ctx context.ContextInterface) *DockerHelper {
	return &DockerHelper{
		ConfigHandler: configHandler,
		Shell:         shell,
		Context:       ctx,
	}
}

// GetEnvVars retrieves Docker-specific environment variables for the current context
func (h *DockerHelper) GetEnvVars() (map[string]string, error) {
	// Get the configuration root directory
	configRoot, err := h.Context.GetConfigRoot()
	if err != nil {
		return nil, fmt.Errorf("error retrieving config root: %w", err)
	}

	// Check for the existence of docker-compose.yaml or docker-compose.yml
	var composeFilePath string
	yamlPath := filepath.Join(configRoot, "docker-compose.yaml")
	ymlPath := filepath.Join(configRoot, "docker-compose.yml")

	if _, err := os.Stat(yamlPath); err == nil {
		composeFilePath = yamlPath
	} else if _, err := os.Stat(ymlPath); err == nil {
		composeFilePath = ymlPath
	}

	envVars := map[string]string{
		"COMPOSE_FILE": composeFilePath,
	}

	return envVars, nil
}

// PostEnvExec runs any necessary commands after the environment variables have been set.
func (h *DockerHelper) PostEnvExec() error {
	return nil
}

// SetConfig sets the configuration value for the given key
func (h *DockerHelper) SetConfig(key, value string) error {
	// This is a stub implementation
	return nil
}

// writeDockerComposeFile is a private method to write the docker-compose configuration to a file.
func (h *DockerHelper) writeDockerComposeFile(newConfigData interface{}, filePath string) error {
	headerComment := "# This file was generated by the Windsor CLI. Do not alter.\n\n"

	// Read existing YAML file if it exists
	existingData := make(map[string]interface{})
	if _, err := os.Stat(filePath); err == nil {
		fileContent, err := ioutil.ReadFile(filePath)
		if err != nil {
			return fmt.Errorf("failed to read existing file: %w", err)
		}
		if err := yaml.Unmarshal(fileContent, &existingData); err != nil {
			return fmt.Errorf("failed to unmarshal existing YAML: %w", err)
		}
	}

	// Merge newConfigData into existingData
	for key, value := range newConfigData.(map[string]interface{}) {
		existingData[key] = value
	}

	// Marshal the merged data
	yamlData, err := yaml.Marshal(existingData)
	if err != nil {
		return fmt.Errorf("failed to marshal YAML: %w", err)
	}

	// Write the merged data back to the file
	file, err := os.Create(filePath)
	if err != nil {
		return fmt.Errorf("failed to create file: %w", err)
	}
	defer file.Close()

	_, err = file.WriteString(headerComment)
	if err != nil {
		return fmt.Errorf("failed to write header comment: %w", err)
	}

	_, err = file.Write(yamlData)
	if err != nil {
		return fmt.Errorf("failed to write YAML data: %w", err)
	}

	return nil
}

// GetContainerConfig returns a list of container data for docker-compose.
func (h *DockerHelper) GetContainerConfig() ([]map[string]interface{}, error) {
	// Stub implementation
	return nil, nil
}

// Ensure DockerHelper implements Helper interface
var _ Helper = (*DockerHelper)(nil)
