package awsprofile

import (
	"os"
	"path/filepath"
	"testing"
)

// writeAWSDir creates a fresh .aws/ directory under a temp root and writes the
// supplied config and credentials bodies. Returns the root path. Use for
// ForContext tests where the resolver derives paths from configRoot/.aws/.
func writeAWSDir(t *testing.T, configBody, credentialsBody string) string {
	t.Helper()
	root := t.TempDir()
	awsDir := filepath.Join(root, ".aws")
	if err := os.MkdirAll(awsDir, 0755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	if configBody != "" {
		if err := os.WriteFile(filepath.Join(awsDir, "config"), []byte(configBody), 0644); err != nil {
			t.Fatalf("write config: %v", err)
		}
	}
	if credentialsBody != "" {
		if err := os.WriteFile(filepath.Join(awsDir, "credentials"), []byte(credentialsBody), 0644); err != nil {
			t.Fatalf("write credentials: %v", err)
		}
	}
	return root
}

// pointAmbientAt writes the supplied bodies into a fresh tmp dir and sets
// AWS_CONFIG_FILE / AWS_SHARED_CREDENTIALS_FILE so Ambient() resolves to them.
// Used to keep Ambient tests deterministic regardless of the developer's
// actual ~/.aws/ contents.
func pointAmbientAt(t *testing.T, configBody, credentialsBody string) {
	t.Helper()
	dir := t.TempDir()
	configPath := filepath.Join(dir, "config")
	credentialsPath := filepath.Join(dir, "credentials")
	if err := os.WriteFile(configPath, []byte(configBody), 0644); err != nil {
		t.Fatalf("write config: %v", err)
	}
	if err := os.WriteFile(credentialsPath, []byte(credentialsBody), 0644); err != nil {
		t.Fatalf("write credentials: %v", err)
	}
	t.Setenv("AWS_CONFIG_FILE", configPath)
	t.Setenv("AWS_SHARED_CREDENTIALS_FILE", credentialsPath)
}

func TestForContext_HasProfile(t *testing.T) {
	t.Run("ReturnsFalseWhenAWSDirMissing", func(t *testing.T) {
		// Given a fresh context root with no .aws/ subdirectory
		root := t.TempDir()

		// When asking whether a named profile exists
		got := ForContext(root).HasProfile("prod")

		// Then the helper returns false without erroring on the missing files
		if got {
			t.Errorf("expected false for missing .aws/, got true")
		}
	})

	t.Run("ReturnsTrueForNamedProfileInConfig", func(t *testing.T) {
		// Given a config file that declares [profile prod] alongside another section
		root := writeAWSDir(t, "[profile staging]\nregion = us-east-1\n\n[profile prod]\nregion = us-west-2\n", "")

		// When asking for prod
		got := ForContext(root).HasProfile("prod")

		// Then the helper finds it
		if !got {
			t.Errorf("expected true for [profile prod] in config, got false")
		}
	})

	t.Run("ReturnsTrueForNamedProfileInCredentials", func(t *testing.T) {
		// Given a credentials file using the unprefixed [prod] section header
		root := writeAWSDir(t, "", "[prod]\naws_access_key_id = AKIA...\naws_secret_access_key = secret\n")

		// When asking for prod
		got := ForContext(root).HasProfile("prod")

		// Then the helper finds it
		if !got {
			t.Errorf("expected true for [prod] in credentials, got false")
		}
	})

	t.Run("ReturnsTrueForDefaultProfileInConfig", func(t *testing.T) {
		// Given a config file containing the [default] section (no "profile " prefix)
		root := writeAWSDir(t, "[default]\nregion = us-west-2\n", "")

		// When asking for default
		got := ForContext(root).HasProfile("default")

		// Then the helper finds it via the [default] header form
		if !got {
			t.Errorf("expected true for [default] in config, got false")
		}
	})

	t.Run("ReturnsFalseWhenOnlyOtherProfilesPresent", func(t *testing.T) {
		// Given a config that defines other profiles but not the one we ask about
		root := writeAWSDir(t, "[profile staging]\nregion = us-east-1\n", "[other]\naws_access_key_id = AKIA\n")

		// When asking for prod
		got := ForContext(root).HasProfile("prod")

		// Then the helper returns false — neither file contains the named section
		if got {
			t.Errorf("expected false when prod absent from both files, got true")
		}
	})

	t.Run("MatchesSectionHeaderWithTrailingInlineComment", func(t *testing.T) {
		// Given a hand-edited config where the section header carries an inline
		// comment after the closing bracket — the aws CLI never writes these but
		// nothing stops an operator from adding one. The match should strip the
		// trailing #/; comment before comparing so the profile is still found.
		root := writeAWSDir(t, "[profile prod] # auto-generated by terraform\nregion = us-west-2\n", "")

		// When asking for prod
		got := ForContext(root).HasProfile("prod")

		// Then the helper still finds the section despite the trailing comment
		if !got {
			t.Errorf("expected true for [profile prod] with trailing inline comment, got false")
		}
	})

	t.Run("IgnoresLookAlikeHeadersInsideConfigFile", func(t *testing.T) {
		// Given a config that names "prod" in unrelated positions but never as a section header
		root := writeAWSDir(t, "[profile staging]\n# comment about [profile prod]\nrole_arn = arn:aws:iam::1:role/prod\n", "")

		// When asking for prod
		got := ForContext(root).HasProfile("prod")

		// Then the helper does not false-positive on the comment or the role arn
		if got {
			t.Errorf("expected false when prod appears only inside other sections, got true")
		}
	})
}

func TestAmbient_HasProfile(t *testing.T) {
	t.Run("FindsProfileInRedirectedConfigFile", func(t *testing.T) {
		// Given AWS_CONFIG_FILE points at a file containing [profile prod]
		pointAmbientAt(t, "[profile prod]\nregion = us-west-2\n", "")

		// When asking for prod
		got := Ambient().HasProfile("prod")

		// Then Ambient honors AWS_CONFIG_FILE and finds the section
		if !got {
			t.Errorf("expected true for [profile prod] in AWS_CONFIG_FILE redirect, got false")
		}
	})

	t.Run("ReturnsFalseWhenRedirectedConfigLacksProfile", func(t *testing.T) {
		// Given AWS_CONFIG_FILE points at an empty file (CI runner with OIDC
		// env-var credentials and no ~/.aws/config — the bug scenario)
		pointAmbientAt(t, "", "")

		// When asking for aws
		got := Ambient().HasProfile("aws")

		// Then the helper returns false so callers omit AWS_PROFILE and let
		// the SDK's credential chain run against env keys / IMDS
		if got {
			t.Errorf("expected false for missing profile in ambient config, got true")
		}
	})

	t.Run("FallsBackToHomeDotAwsWhenEnvUnset", func(t *testing.T) {
		// Given neither AWS_CONFIG_FILE nor AWS_SHARED_CREDENTIALS_FILE is set,
		// and HOME points at a controlled temp dir containing a profile
		home := t.TempDir()
		awsDir := filepath.Join(home, ".aws")
		if err := os.MkdirAll(awsDir, 0755); err != nil {
			t.Fatalf("mkdir: %v", err)
		}
		if err := os.WriteFile(filepath.Join(awsDir, "config"), []byte("[profile localdev]\nregion = us-east-1\n"), 0644); err != nil {
			t.Fatalf("write: %v", err)
		}
		t.Setenv("AWS_CONFIG_FILE", "")
		t.Setenv("AWS_SHARED_CREDENTIALS_FILE", "")
		t.Setenv("HOME", home)

		// When asking for localdev
		got := Ambient().HasProfile("localdev")

		// Then the fallback path resolves to $HOME/.aws/config and finds it
		if !got {
			t.Errorf("expected true when profile defined in $HOME/.aws/config, got false")
		}
	})
}
