name: cli-pages
on:
  push:
    branches:
      - mkdocs
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config --global user.name github-actions[bot]
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Trigger WindsorCLI Build
        env:
          GH_TOKEN: ${{ secrets.GHTOKEN }}
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token $GH_TOKEN" \
            https://api.github.com/repos/windsor-hotel/windsorcli/dispatches \
            -d '{"event_type": "build_event"}'
