name: 'Create Release Branch'

on:
  workflow_dispatch:
    inputs:
      src_branch:
        description: 'Source Branch'
        required: false
        default: 'main'
      release:
        description: 'Release Branch: [latest, release-x.y.z, x.y.z]'
        required: false
        default: 'latest'
  
jobs:
  create-release-branch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          # ref: main
          ref: release-process

      - name: Run Create Release Branch Action
        uses: windsorcli/windsortest/.github/actions/create-release-branch@release-process
        with:
          src_branch: ${{ inputs.src_branch }}
          release: ${{ inputs.release }}
          token: ${{ secrets.GH_TOKEN }}