name: 'Create Docs Branch'

on:
  workflow_dispatch:
    inputs:
      src_branch:
        description: 'Source Branch'
        required: false
        default: 'main'
      docs:
        description: 'Docs Branch'
        required: false
        default: 'latest'

jobs:
  create-docs-branch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Run Create Docs Branch Action
        uses: windsorcli/blueprint/.github/actions/create-docs-branch@release-process
        with:
          src_branch: ${{ inputs.src_branch }}
          docs: ${{ inputs.docs }}
          token: ${{ secrets.GH_TOKEN }}