name: 'Run Integration Test'

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Release Branch: [latest, release-x.y.z, x.y.z]'
        required: false
        default: 'latest'

jobs:
  run-integration-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2
      with:
        ref: main
      
    - name: Run Integration Test Action
      uses: windsorcli/blueprint/.github/actions/run-integration-test@release-process
      with:
        release: ${{ inputs.release }}   
        token: ${{ secrets.GH_TOKEN }}  

  