name: 'Test and Release'

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Release Branch: [latest, release-x.y.z, x.y.z]'
        required: false
        default: 'latest'

jobs:
  test-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          # ref: main
          ref: release-process

      - name: Run Test and Release Action
        uses: windsorcli/windsortest/.github/actions/test-and-release@release-process
        with:
          release: ${{ inputs.release }}
          token: ${{ secrets.GH_TOKEN }}
